CREATE TABLE STUDENT(
    ID INT PRIMARY KEY,
    NAME VARCHAR(20),
    BRANCH VARCHAR(20)
);
CREATE TABLE MARKS(
    ID INT PRIMARY KEY,
    JAVA INT,
    PYTHON INT,
    DS INT,
    STUDENTID INT,
    FOREIGN KEY(STUDENTID) REFERENCES STUDENT(ID)
);
INSERT INTO STUDENT VALUES(1,"SHAM","ECE");
INSERT INTO MARKS VALUES(1,20,30,40,1);
SELECT * FROM STUDENT;
SELECT * FROM MARKS;